# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node runtime as a parent image
FROM node:22-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install any needed packages
RUN npm install

# Copy the current directory contents into the container at /app
COPY . .

# Build the app
RUN npm run build

# Use a lighter weight image for production
FROM node:18-alpine AS runner

# Set the working directory in the container
WORKDIR /app

# Copy the build artifacts and node_modules from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Set environment variables for MCP server
# ENV MCP_HF_WORK_DIR=/your_directory
# ENV HF_TOKEN=hf_your_token

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the application
ENTRYPOINT ["node", "build/index.js"]

# Command to run the MCP server with default HuggingFace spaces
# CMD ["--work-dir=/your_directory", "evalstate/FLUX.1-schnell"]
